### ISSUE TITLE
Visually distinguish "raw" vs. "phylo" display? [Enhancement]

### ISSUE THREAD

**Issue by jimallman** [blackrim/opentreemaps#3]
I think it's too easy to lose track of which values are currently being shown. Perhaps use a different color scale (blue/green vs. red/yellow) for each?

If it's easy, it would be great to express this choice (D vs. P) through the UI. My preference would be a pair of mutually-exclusive sticky buttons, with the currently active option cleary selected.

**Comment by blackrim** [comment]
I did the color change here c7963f7 and will look at doing a toggle
